paths:
  
  # Path to FASTA file with all proteins (concatenated) in the dataset
  proteins: data/Plasmid_Protein_Database/proteins.faa
  # Path to folder with plasmid nucleotide FASTA
  plasmids: 'data/Plasmid FASTA'
  # Path to folder with concatenated plasmid nucleotide FASTA
  raw_plasmids: 'data/Concatenated Plasmid FASTA'
  # Path to folder with plasmids GenBank feature files
  plasmids_gb: 'data/Plasmid_Features'
  # Path to folder with txt AMRFinder output
  amrfinder_output: 'data/AMRFinder_Output'
  # Path to plasmid info CSV
  info_df: 'data/plasmid_info.tsv'
  # Path to CSV with concatenated AMRFinder output
  amr_hits: 'data/AMRFinder_Output/amr_hits.tsv'
  # Path to plasmid annotations
  annotations: 'data/Annotations'
  # Path to MOBSuite input files
  mob-suite: 'data/MOBSuite Input'
  # Path to MOBSuite output files
  mob-types: 'data/MOB Types'
  # Plasmid FASTA concatenated per species
  concat-fasta: 'data/Concatenated_Plasmid_FASTA'
