paths:
  plasmid-clusters: data/Jaccard Clusters/Clusters.pkl
  representative-proteins: data/Homolog Clusters/Protein Family Membership/protein_cluster_membership_s0.9_k5.tsv # os.path.join(tmp_path, 'protein_cluster_membership.tsv')
  protein-names: data/Homolog Clusters/Protein Family Membership/Protein Clusters.tsv
  sequences: data/Homolog Clusters/Representative Proteins/Plasmids with Clustered Proteins.pkl

output: data/Plasmid Networks
output-paths:
  sub-clusters: Jaccard-Subclusters.tsv
  phylogenies: Jaccard-Phylogenies.pkl
  pangenomes: Pangenome-Graph-
  linkage: Linkage-and-Labels-Cluster-
  logfile: parameters.txt

similarity: jaccard # ani or jaccard

n_cds:
  drop: True
  threshold: 0

clusters:
  - 0
  - 5
  - 10
  - 16
  - 37

agglomerative-clustering:
  linkage: average
  distance-threshold: .4
  adaptative: True

learn-weights: True
learning-method: max-likelihood # ratio, precomputed or max-likelihood
weights: 
  mutation: 1
  mobile element: 1
  recombination: 20
  reversal: 1
  transposition: 1
  duplicate: 1

break-distance:
  k: 3
  indel-size-penalty: 0.5

results-dir: data/Plasmid Networks